import {
  AppWindow,
  ArrowDownToLine,
  ArrowRight,
  ArrowUpRight,
  AudioLines,
  Braces,
  CaseSensitive,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeftRight,
  Clapperboard,
  CodeXml,
  Combine,
  Cpu,
  Crop,
  Download,
  Ellipsis,
  Eraser,
  FileArchive,
  FileAudio,
  FileImage,
  FileLock2,
  FileText,
  FileX2,
  Files,
  Film,
  Fingerprint,
  FolderOpen,
  Gauge,
  GitCompare,
  Globe,
  HardDrive,
  Hash,
  House,
  Image,
  ImagePlus,
  Images,
  KeyRound,
  LayoutGrid,
  Link2,
  List,
  Loader,
  MapPinOff,
  Maximize,
  Maximize2,
  Menu,
  Mic,
  Minimize2,
  Minus,
  MonitorDown,
  Moon,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pipette,
  Plus,
  QrCode,
  Regex,
  Repeat,
  RotateCcw,
  RotateCw,
  Scaling,
  ScanFace,
  ScanText,
  Scissors,
  Search,
  Shield,
  ShieldCheck,
  Signature,
  Sigma,
  SlidersHorizontal,
  Smartphone,
  Speech,
  SplitSquareHorizontal,
  Stamp,
  Sun,
  SunMoon,
  Table,
  Tag,
  TrendingDown,
  TriangleAlert,
  Type,
  Upload,
  Video,
  VideoOff,
  Volume2,
  WifiOff,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Explicit map from the lucide icon names used in the design to components.
 * Keeping it explicit keeps lucide tree-shakeable.
 */
export const icons = {
  "app-window": AppWindow,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "audio-lines": AudioLines,
  braces: Braces,
  "case-sensitive": CaseSensitive,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-left-right": ChevronsLeftRight,
  clapperboard: Clapperboard,
  "code-xml": CodeXml,
  combine: Combine,
  cpu: Cpu,
  crop: Crop,
  download: Download,
  ellipsis: Ellipsis,
  eraser: Eraser,
  "file-archive": FileArchive,
  "file-audio": FileAudio,
  "file-image": FileImage,
  "file-lock-2": FileLock2,
  "file-text": FileText,
  "file-x-2": FileX2,
  files: Files,
  film: Film,
  fingerprint: Fingerprint,
  "folder-open": FolderOpen,
  gauge: Gauge,
  "git-compare": GitCompare,
  globe: Globe,
  "hard-drive": HardDrive,
  hash: Hash,
  house: House,
  image: Image,
  "image-plus": ImagePlus,
  images: Images,
  "key-round": KeyRound,
  "layout-grid": LayoutGrid,
  "link-2": Link2,
  list: List,
  loader: Loader,
  "map-pin-off": MapPinOff,
  maximize: Maximize,
  "maximize-2": Maximize2,
  menu: Menu,
  mic: Mic,
  "minimize-2": Minimize2,
  minus: Minus,
  "monitor-down": MonitorDown,
  moon: Moon,
  palette: Palette,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  pipette: Pipette,
  plus: Plus,
  "qr-code": QrCode,
  regex: Regex,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  scaling: Scaling,
  "scan-face": ScanFace,
  "scan-text": ScanText,
  scissors: Scissors,
  search: Search,
  shield: Shield,
  "shield-check": ShieldCheck,
  signature: Signature,
  sigma: Sigma,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  speech: Speech,
  "split-square-horizontal": SplitSquareHorizontal,
  stamp: Stamp,
  sun: Sun,
  "sun-moon": SunMoon,
  table: Table,
  tag: Tag,
  "trending-down": TrendingDown,
  "triangle-alert": TriangleAlert,
  type: Type,
  upload: Upload,
  video: Video,
  "video-off": VideoOff,
  "volume-2": Volume2,
  "wifi-off": WifiOff,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function getIcon(name: IconName): LucideIcon {
  return icons[name];
}
