import { categories, categoryList } from "./categories";
import type { Category, CategoryDefinition, ToolDefinition } from "./types";

const MB = 1024 * 1024;
const GB = 1024 * MB;

const IMAGE = ["image/jpeg", "image/png", "image/webp", "image/avif", "image/gif", "image/heic", "image/heif", ".heic"];
const AUDIO = ["audio/*", ".m4a", ".flac"];
const VIDEO = ["video/mp4", "video/webm", "video/quicktime", ".mov"];
const PDF = ["application/pdf"];

/** Placeholder until each phase lands its real component. */
const placeholder = () => import("@/tools/placeholder/PlaceholderTool");

/**
 * Single source of truth for all tools.
 * Sidebar, search, home grid, category pages, routes and SEO metadata derive from this list.
 * Adding a tool = one entry here + one component folder.
 */
export const tools: ToolDefinition[] = [
  // ───────── Images ─────────
  {
    slug: "compress",
    category: "image",
    name: "Compress image",
    description: "Shrink JPG, PNG and WebP without visible quality loss.",
    shortDescription: "Shrink JPG, PNG and WebP",
    icon: "minimize-2",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["optimize", "reduce", "smaller", "quality"],
    popular: true,
    component: placeholder,
  },
  {
    slug: "resize",
    category: "image",
    name: "Resize image",
    description: "Exact pixels, percentage or social presets.",
    icon: "scaling",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["scale", "dimensions", "width", "height"],
    popular: true,
    component: placeholder,
  },
  {
    slug: "crop",
    category: "image",
    name: "Crop image",
    description: "Free-form or fixed ratios like 1:1 and 16:9.",
    icon: "crop",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["aspect", "ratio", "trim"],
    component: placeholder,
  },
  {
    slug: "convert",
    category: "image",
    name: "Convert format",
    description: "JPG, PNG, WebP, AVIF and back again.",
    icon: "repeat",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["jpg to png", "png to webp", "avif", "change format"],
    component: placeholder,
  },
  {
    slug: "rotate",
    category: "image",
    name: "Rotate & flip",
    description: "Fix orientation in one click, losslessly.",
    icon: "rotate-cw",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["mirror", "orientation", "turn"],
    component: placeholder,
  },
  {
    slug: "watermark",
    category: "image",
    name: "Add watermark",
    description: "Text or logo, positioned or tiled.",
    icon: "stamp",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["logo", "copyright", "brand"],
    component: placeholder,
  },
  {
    slug: "filters",
    category: "image",
    name: "Filters & adjust",
    description: "Brightness, contrast, saturation, presets.",
    icon: "sliders-horizontal",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["grayscale", "blur", "adjustments", "effects"],
    component: placeholder,
  },
  {
    slug: "remove-exif",
    category: "image",
    name: "Remove EXIF data",
    description: "Strip GPS location and camera details from photos.",
    shortDescription: "Strip location from photos",
    icon: "map-pin-off",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["metadata", "privacy", "gps", "strip"],
    popular: true,
    component: placeholder,
  },
  {
    slug: "heic-to-jpg",
    category: "image",
    name: "HEIC to JPG",
    description: "Open iPhone photos anywhere.",
    icon: "smartphone",
    accept: ["image/heic", "image/heif", ".heic", ".heif"],
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["iphone", "apple", "heif"],
    component: placeholder,
  },
  {
    slug: "images-to-pdf",
    category: "image",
    name: "Images to PDF",
    description: "Combine photos into a single document.",
    icon: "file-image",
    accept: IMAGE,
    multiple: true,
    maxSize: 100 * MB,
    keywords: ["jpg to pdf", "png to pdf", "document"],
    component: placeholder,
  },
  {
    slug: "favicon",
    category: "image",
    name: "Favicon maker",
    description: "Generate every icon size from one image.",
    icon: "app-window",
    accept: ["image/png", "image/jpeg", "image/webp", "image/svg+xml"],
    multiple: false,
    maxSize: 20 * MB,
    keywords: ["app icon", "ico", "pwa", "manifest"],
    component: placeholder,
  },

  // ───────── Audio ─────────
  {
    slug: "trim",
    category: "audio",
    name: "Trim audio",
    description: "Cut, fade and export to MP3, WAV or OGG.",
    icon: "scissors",
    accept: AUDIO,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["cut", "clip", "ringtone"],
    popular: true,
    component: placeholder,
  },
  {
    slug: "convert",
    category: "audio",
    name: "Convert audio",
    description: "MP3, WAV, OGG and M4A with a bitrate of your choice.",
    icon: "repeat",
    accept: AUDIO,
    multiple: true,
    maxSize: 500 * MB,
    keywords: ["mp3", "wav", "ogg", "m4a", "bitrate"],
    component: placeholder,
  },
  {
    slug: "volume",
    category: "audio",
    name: "Change volume",
    description: "Boost or lower the level without clipping.",
    icon: "volume-2",
    accept: AUDIO,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["gain", "louder", "quieter"],
    component: placeholder,
  },
  {
    slug: "fade",
    category: "audio",
    name: "Fade in & out",
    description: "Smooth starts and endings with adjustable curves.",
    icon: "gauge",
    accept: AUDIO,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["fade in", "fade out"],
    component: placeholder,
  },
  {
    slug: "speed",
    category: "audio",
    name: "Change speed",
    description: "Speed up or slow down, with or without pitch change.",
    icon: "gauge",
    accept: AUDIO,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["tempo", "pitch", "faster", "slower"],
    component: placeholder,
  },
  {
    slug: "normalize",
    category: "audio",
    name: "Normalize volume",
    description: "Bring every clip to a consistent loudness.",
    icon: "audio-lines",
    accept: AUDIO,
    multiple: true,
    maxSize: 500 * MB,
    keywords: ["loudness", "level", "lufs"],
    component: placeholder,
  },
  {
    slug: "merge",
    category: "audio",
    name: "Merge audio",
    description: "Join several clips into one file.",
    icon: "combine",
    accept: AUDIO,
    multiple: true,
    maxSize: 500 * MB,
    keywords: ["join", "concatenate", "combine"],
    component: placeholder,
  },
  {
    slug: "record",
    category: "audio",
    name: "Voice recorder",
    description: "Record from your microphone and download the take.",
    icon: "mic",
    accept: [],
    multiple: false,
    keywords: ["microphone", "memo", "capture"],
    component: placeholder,
  },

  // ───────── Video ─────────
  {
    slug: "trim",
    category: "video",
    name: "Trim video",
    description: "Cut a clip to the exact start and end you need.",
    icon: "scissors",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["cut", "clip"],
    component: placeholder,
  },
  {
    slug: "compress",
    category: "video",
    name: "Compress video",
    description: "Pick a resolution and quality, see the estimated size.",
    icon: "minimize-2",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["reduce", "smaller", "bitrate"],
    component: placeholder,
  },
  {
    slug: "convert",
    category: "video",
    name: "Convert video",
    description: "MP4 to WebM and back.",
    icon: "repeat",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["mp4", "webm", "mov"],
    component: placeholder,
  },
  {
    slug: "to-gif",
    category: "video",
    name: "Video to GIF",
    description: "Turn short clips into lightweight loops.",
    icon: "film",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["gif", "loop", "animation"],
    popular: true,
    component: placeholder,
  },
  {
    slug: "extract-audio",
    category: "video",
    name: "Extract audio",
    description: "Save the soundtrack as MP3 or WAV.",
    icon: "file-audio",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["mp3", "soundtrack", "rip"],
    component: placeholder,
  },
  {
    slug: "remove-audio",
    category: "video",
    name: "Remove audio",
    description: "Mute a video permanently.",
    icon: "video-off",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["mute", "silent"],
    component: placeholder,
  },
  {
    slug: "crop",
    category: "video",
    name: "Crop video",
    description: "Reframe to 9:16, 1:1 or 16:9.",
    icon: "crop",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["aspect", "ratio", "vertical", "square"],
    component: placeholder,
  },
  {
    slug: "watermark",
    category: "video",
    name: "Watermark video",
    description: "Overlay text or a logo.",
    icon: "stamp",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["logo", "brand", "overlay"],
    component: placeholder,
  },
  {
    slug: "capture-frame",
    category: "video",
    name: "Capture frame",
    description: "Save any frame as a PNG or JPG.",
    icon: "image-plus",
    accept: VIDEO,
    multiple: false,
    maxSize: 2 * GB,
    keywords: ["screenshot", "still", "thumbnail"],
    component: placeholder,
  },
  {
    slug: "record",
    category: "video",
    name: "Screen & webcam recorder",
    description: "Record your screen or camera, then edit the result.",
    icon: "video",
    accept: [],
    multiple: false,
    keywords: ["screen", "webcam", "camera", "capture"],
    component: placeholder,
  },

  // ───────── PDF ─────────
  {
    slug: "merge",
    category: "pdf",
    name: "Merge PDF",
    description: "Combine documents and drag pages into order.",
    shortDescription: "Combine and reorder pages",
    icon: "files",
    accept: PDF,
    multiple: true,
    maxSize: 500 * MB,
    keywords: ["combine", "join"],
    popular: true,
    component: placeholder,
  },
  {
    slug: "split",
    category: "pdf",
    name: "Split PDF",
    description: "Extract a page range or burst into single pages.",
    icon: "split-square-horizontal",
    accept: PDF,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["extract", "pages", "range"],
    component: placeholder,
  },
  {
    slug: "organize",
    category: "pdf",
    name: "Organize pages",
    description: "Reorder, rotate and delete pages in a grid.",
    icon: "layout-grid",
    accept: PDF,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["reorder", "rotate", "delete", "pages"],
    component: placeholder,
  },
  {
    slug: "to-images",
    category: "pdf",
    name: "PDF to images",
    description: "Render every page to PNG or JPG and download a zip.",
    icon: "images",
    accept: PDF,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["png", "jpg", "render", "export"],
    component: placeholder,
  },
  {
    slug: "compress",
    category: "pdf",
    name: "Compress PDF",
    description: "Re-encode embedded images to shrink the file.",
    icon: "minimize-2",
    accept: PDF,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["reduce", "smaller", "optimize"],
    component: placeholder,
  },
  {
    slug: "watermark",
    category: "pdf",
    name: "Watermark PDF",
    description: "Stamp text or an image across every page.",
    icon: "stamp",
    accept: PDF,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["stamp", "draft", "confidential"],
    component: placeholder,
  },
  {
    slug: "page-numbers",
    category: "pdf",
    name: "Add page numbers",
    description: "Numbers in the position and style you choose.",
    icon: "hash",
    accept: PDF,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["footer", "header", "numbering"],
    component: placeholder,
  },
  {
    slug: "sign",
    category: "pdf",
    name: "Sign PDF",
    description: "Draw or upload a signature and place it on a page.",
    icon: "signature",
    accept: PDF,
    multiple: false,
    maxSize: 500 * MB,
    keywords: ["signature", "esign", "initials"],
    component: placeholder,
  },

  // ───────── Text ─────────
  {
    slug: "word-counter",
    category: "text",
    name: "Word & character counter",
    description: "Words, characters, sentences and reading time.",
    icon: "sigma",
    accept: [],
    multiple: false,
    keywords: ["count", "length", "reading time"],
    component: placeholder,
  },
  {
    slug: "case-converter",
    category: "text",
    name: "Case converter",
    description: "UPPER, lower, Title, camelCase, snake_case and more.",
    icon: "case-sensitive",
    accept: [],
    multiple: false,
    keywords: ["uppercase", "lowercase", "title case", "camel"],
    component: placeholder,
  },
  {
    slug: "diff",
    category: "text",
    name: "Text diff",
    description: "Compare two texts line by line.",
    icon: "git-compare",
    accept: [],
    multiple: false,
    keywords: ["compare", "changes", "difference"],
    component: placeholder,
  },
  {
    slug: "markdown",
    category: "text",
    name: "Markdown previewer",
    description: "Write Markdown and see the rendered result live.",
    icon: "file-text",
    accept: [".md", "text/markdown", "text/plain"],
    multiple: false,
    keywords: ["md", "preview", "render"],
    component: placeholder,
  },
  {
    slug: "ocr",
    category: "text",
    name: "Image to text (OCR)",
    description: "Pull editable text out of screenshots and scans.",
    icon: "scan-text",
    accept: IMAGE,
    multiple: false,
    maxSize: 50 * MB,
    keywords: ["ocr", "recognize", "extract text", "scan"],
    component: placeholder,
  },
  {
    slug: "text-to-speech",
    category: "text",
    name: "Text to speech",
    description: "Read any text aloud with your device's voices.",
    icon: "speech",
    accept: [],
    multiple: false,
    keywords: ["tts", "voice", "read aloud"],
    component: placeholder,
  },

  // ───────── Developer ─────────
  {
    slug: "json",
    category: "dev",
    name: "JSON formatter",
    description: "Format, validate and minify JSON instantly.",
    icon: "braces",
    accept: ["application/json", ".json"],
    multiple: false,
    maxSize: 20 * MB,
    keywords: ["pretty print", "validate", "minify", "beautify"],
    popular: true,
    component: placeholder,
  },
  {
    slug: "base64",
    category: "dev",
    name: "Base64 encode & decode",
    description: "Text and files to Base64 and back.",
    icon: "fingerprint",
    accept: [],
    multiple: false,
    keywords: ["encode", "decode", "data uri"],
    component: placeholder,
  },
  {
    slug: "url",
    category: "dev",
    name: "URL encode & decode",
    description: "Escape and unescape URLs and query strings.",
    icon: "link-2",
    accept: [],
    multiple: false,
    keywords: ["percent encoding", "escape", "query string"],
    component: placeholder,
  },
  {
    slug: "jwt",
    category: "dev",
    name: "JWT decoder",
    description: "Inspect header, payload and expiry of a token.",
    icon: "key-round",
    accept: [],
    multiple: false,
    keywords: ["token", "jwt", "claims"],
    component: placeholder,
  },
  {
    slug: "hash",
    category: "dev",
    name: "Hash generator",
    description: "SHA-1, SHA-256 and SHA-512 for text or files.",
    icon: "hash",
    accept: [],
    multiple: false,
    keywords: ["sha256", "checksum", "digest"],
    component: placeholder,
  },
  {
    slug: "uuid",
    category: "dev",
    name: "UUID generator",
    description: "Generate v4 UUIDs one at a time or in bulk.",
    icon: "fingerprint",
    accept: [],
    multiple: false,
    keywords: ["guid", "unique id", "random"],
    component: placeholder,
  },
  {
    slug: "color",
    category: "dev",
    name: "Color converter",
    description: "HEX, RGB and HSL side by side with a live swatch.",
    icon: "pipette",
    accept: [],
    multiple: false,
    keywords: ["hex", "rgb", "hsl", "picker"],
    component: placeholder,
  },
  {
    slug: "palette",
    category: "dev",
    name: "Palette generator",
    description: "Build harmonious palettes from a base color.",
    icon: "palette",
    accept: [],
    multiple: false,
    keywords: ["colors", "scheme", "shades", "tints"],
    component: placeholder,
  },
  {
    slug: "regex",
    category: "dev",
    name: "Regex tester",
    description: "Test patterns with live matches and groups.",
    icon: "regex",
    accept: [],
    multiple: false,
    keywords: ["regular expression", "pattern", "match"],
    component: placeholder,
  },
  {
    slug: "csv",
    category: "dev",
    name: "CSV, JSON & Excel converter",
    description: "Convert tables between CSV, JSON and XLSX.",
    icon: "table",
    accept: [".csv", ".json", ".xlsx", "text/csv", "application/json"],
    multiple: false,
    maxSize: 50 * MB,
    keywords: ["spreadsheet", "xlsx", "table", "convert"],
    component: placeholder,
  },

  // ───────── Privacy ─────────
  {
    slug: "password",
    category: "privacy",
    name: "Password generator",
    description: "Strong random passwords and passphrases.",
    icon: "key-round",
    accept: [],
    multiple: false,
    keywords: ["random", "secure", "passphrase"],
    component: placeholder,
  },
  {
    slug: "encrypt",
    category: "privacy",
    name: "Encrypt & decrypt file",
    description: "Lock any file with a password using AES-GCM.",
    icon: "file-lock-2",
    accept: [],
    multiple: false,
    maxSize: 1 * GB,
    keywords: ["aes", "password", "secure", "lock"],
    component: placeholder,
  },
  {
    slug: "qr",
    category: "privacy",
    name: "QR code generator & scanner",
    description: "Make QR codes or read them from an image.",
    icon: "qr-code",
    accept: IMAGE,
    multiple: false,
    maxSize: 20 * MB,
    keywords: ["qr", "scan", "barcode"],
    component: placeholder,
  },
  {
    slug: "zip",
    category: "privacy",
    name: "Zip & unzip",
    description: "Bundle files into a zip or extract one.",
    icon: "file-archive",
    accept: [],
    multiple: true,
    maxSize: 2 * GB,
    keywords: ["archive", "compress", "extract"],
    component: placeholder,
  },
];

// ───────── Lookups ─────────

export function toolPath(tool: Pick<ToolDefinition, "category" | "slug">): string {
  return `/${tool.category}/${tool.slug}`;
}

export function categoryPath(category: Category): string {
  return `/${category}`;
}

export function isCategory(value: string): value is Category {
  return value in categories;
}

export function getCategory(slug: string): CategoryDefinition | undefined {
  return isCategory(slug) ? categories[slug] : undefined;
}

export function getTool(category: string, slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.category === category && t.slug === slug);
}

export function toolsIn(category: Category): ToolDefinition[] {
  return tools.filter((t) => t.category === category);
}

export function toolCount(category: Category): number {
  return toolsIn(category).length;
}

export const popularTools: ToolDefinition[] = tools.filter((t) => t.popular);

export { categories, categoryList };
